### ISSUE TITLE
安装不成功，求帮助，谢谢

### ISSUE THREAD

**Issue by xiongc** [zensh/jsgen#72]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

D:\WebSite\jsgen>npm start

> jsgen@0.8.6 start D:\WebSite\jsgen
> node app.js

rrestjs process 9532 Checking config file starting...
check config file error: TypeError: undefined is not a function
rrestjs process 9532 Config file checking complete, errors:0/73, warns:0/73
{ [ReferenceError: D:\WebSite\jsgen\node_modules\rrestjs\node_modules\mongodb\li
b\mongodb\db.js:869
      || (selector['mapreduce'] && selector.out = 'inline')) {
          ^^^^^^^^
Invalid left-hand side in assignment] domainThrown: true }
D:\WebSite\jsgen\node_modules\rrestjs\node_modules\mongodb\lib\mongodb\db.js:869

      || (selector['mapreduce'] && selector.out = 'inline')) {
          ^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at D:\WebSite\jsgen\node_modules\rrestjs\node_modules\mongodb\lib\mongodb\in
dex.js:29:17
    at Array.forEach (native)
    at Object.<anonymous> (D:\WebSite\jsgen\node_modules\rrestjs\node_modules\mo
ngodb\lib\mongodb\index.js:28:25)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! jsgen@0.8.6 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jsgen@0.8.6 start script 'node app.js'.
npm ERR! This is most likely a problem with the jsgen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls jsgen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\WebSite\jsgen\npm-debug.log

D:\WebSite\jsgen>

**Comment by zensh** [comment]
依赖程序版本很老了，没办法更新了

**Comment by xiongc** [comment]
怎么解决啊？

**Comment by zensh** [comment]
应该是解决不了了，我也不想重构。linux 下安装应该问题不大，另外必须要 node.js v0.10.x
