### ISSUE TITLE
npm start 报错

### ISSUE THREAD

**Issue by passballking** [zensh/jsgen#74]
按照教程把mongoskin的版本改成1.4.x，然后npm install都是好的，但是npmstart失败，请问是什么问题？
> jsgen@0.8.6 start /home/taoqin/Desktop/angularNode/jsgen
> node app.js

rrestjs process 27459 Checking config file starting...
check config file error: TypeError: check[key] is not a function
rrestjs process 27459 Config file checking complete, errors:0/73, warns:0/73
{ [ReferenceError: Invalid left-hand side in assignment] domainThrown: true }
/home/taoqin/Desktop/angularNode/jsgen/app.js:22
    jsGen.serverlog.error(error);
                   ^

TypeError: Cannot read property 'error' of undefined
    at Domain.<anonymous> (/home/taoqin/Desktop/angularNode/jsgen/app.js:22:20)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
    at emitError (domain.js:65:24)
    at Domain.errorHandler [as _errorHandler] (domain.js:104:16)
    at process._fatalException (node.js:220:33)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! jsgen@0.8.6 start: `node app.js`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the jsgen@0.8.6 start script 'node app.js'.
npm ERR! This is most likely a problem with the jsgen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls jsgen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/taoqin/Desktop/angularNode/jsgen/npm-debug.log

**Comment by zensh** [comment]
Hi, 真是抱歉，由于工作太忙，这个项目已经很久没有维护了，所有依赖都已经很老了。

**Comment by passballking** [comment]
严哥您好啊！能得到您的回复真是幸会！我是自学node 从java backend
跳到前台，想通过学习您的这个项目来自学搭建第一个网站。我想问一下您搭建网站大概有那几块？我从angularjs.cn 学到的是  mongodb+
redis + 业务逻辑 + angular js 的前台，请问现在还是这种架构么？另外我想问一下实战中一般是用 token 验证还是 cookie
验证啊？

2015-12-13 23:48 GMT-05:00 Yan Qing <notifications@github.com>:

**Comment by zensh** [comment]
我却正在学 java~
搭网站 jsgen 另外需要 mongodb 和 redis。
验证应该是能用 token 就用 token，但很多场景不得不用 cookie，所以通常两者都要用。

另外 jsgen 有两个问题：一是含有状态，无法启用多线程；二是很多逻辑不标准（都是自己实现，应该用通用的第三方库来取代）~

**Comment by deo24** [comment]
怎么解决 遇到同样的问题！！！
