### ISSUE TITLE
check config file error: TypeError: check[key] is not a function rrestjs process 53266 Config file checking complete, errors:0/73, warns:0/73

### ISSUE THREAD

**Issue by 2013yulong** [zensh/jsgen#77]
check config file error: TypeError: check[key] is not a function
rrestjs process 53266 Config file checking complete, errors:0/73, warns:0/73
怀疑是api文件夹里面缺少 install.js文件吧 初始化失败

**Comment by DavidYangNO1** [comment]
你这么解决的 一样的问题
